# Generated by Django 4.1.13 on 2024-10-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
