# Generated by Django 4.2 on 2024-10-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delete_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondhand',
            field=models.BooleanField(default=False, help_text='0-show,1-Hidden'),
        ),
    ]
