# Generated by Django 4.2 on 2024-10-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_secondhand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='secondhand',
        ),
    ]
